version: '3'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tgbot
    #volumes:
    #  - database-data:/var/lib/postgresql/data/

  migrate:
    image: migrate/migrate
    volumes:
    - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:tgbot@db:5432/postgres?sslmode=disable", "up"]
    depends_on:
      - db

  app:
    image: ghcr.io/eretic431/datingtelegrambot:latest
    restart: unless-stopped
    environment:
      - BOT_TOKEN=5085296878:AAFm-DFK-_S0Eg7GpXhkq0S6XN1W9BhLVLU
    depends_on:
      - db
      - migrate

#volumes:
#  database-data:
