version: '3'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tgbot
    volumes:
      - database-data:/var/lib/postgresql/data/

  migrate:
    image: migrate/migrate
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:tgbot@db:5432/postgres?sslmode=disable", "up" ]
    depends_on:
      - db

  app:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=5085296878:AAFm-DFK-_S0Eg7GpXhkq0S6XN1W9BhLVLU
      - POSTGRES_URL=postgres://postgres:tgbot@db:5432/postgres?sslmode=disable
    ports:
      - "8090:8090"
    depends_on:
      - db
      - migrate

  dozzle:
    image: amir20/dozzle:latest
    container_name: bot-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"

volumes:
  database-data:
