version: '3'

services:
  db:
    container_name: bot-postgres
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

  migrate:
    container_name: bot-migrate
    image: migrate/migrate
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    command: [ "-path", "/migrations", "-database", "${POSTGRES_URL}", "up" ]
    depends_on:
      - db

  app:
    container_name: bot-app
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - migrate

  dozzle:
    image: amir20/dozzle:latest
    container_name: bot-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"

volumes:
  database-data:
