name: Test
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: tgbot
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    name: checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - name: Install golang-migrate
      run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate
    - run: make migrate_up
    - run: go test ./cmd/api -v
    - run: go test ./internal/usecase ./internal/data/postgres -v

    - run: docker-compose up --build -d

    - name: Set up Python for system testing
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.12

    - name: Install dependenices for system testing
      run: |
        python -m pip install --upgrade pip
        cd system_tests
        pip install -r requirements.txt

    - name: Run system tests
      run: |
        cd system_tests
        pytest -s main.py
